/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "tbprobe.h"
/* Header for class TB_Tablebase */

#ifndef _Included_TB_Tablebase
#define _Included_TB_Tablebase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TB_Tablebase
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TB_Tablebase_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     TB_Tablebase
 * Method:    probeDTZ
 * Signature: (JJJJJJJJIJJZ)J
 */
JNIEXPORT jlong JNICALL Java_TB_Tablebase_probeDTZ
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jint, jlong, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
